name: trivy-scan-Pipeline
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  trivy-scan:
    name: trivy scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in config mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
        exit-code: '0'
        format: 'table'