name: ZAP API Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-api-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://your-api-endpoint.com/openapi.json'  # Replace with your API specification URL
          format: openapi  # Options: openapi, soap, or graphql
          # rules_file_name: '.zap/rules.tsv'  # Uncomment if you have custom rules
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # cmd_options: '-a'  # Uncomment to add additional command line options
          issue_title: 'ZAP API Security Scan Report'
          #fail_action: true  # Fail the workflow if vulnerabilities are found
          allow_issue_writing: false
          artifact_name: 'zap-api-scan-results'
